const products = [
    {
      id: 1,
      category: "인형",
      brand: "WitchA",
      productName: "재인 인형",
      image: "",
      price: "18000",
      description: "어쩌구 저쩌구 훌라 훌라 훌라 나는야~~ 멋진 토마토 빰빰@!",
      personType: "A",
    },
    {
      id: 2,
      category: "인형",
      brand: "WitchA",
      productName: "갑열 인형",
      image: "",
      price: "18000",
      description: "어쩌구 저쩌구 훌라 훌라 훌라 나는야~~ 멋진 토마토 빰빰@!",
      personType: "B",
    },
    {
      id: 3,
      category: "인형",
      brand: "WitchB",
      productName: "은비 인형",
      image: "",
      price: "18000",
      description: "어쩌구 저쩌구 훌라 훌라 훌라 나는야~~ 멋진 토마토 빰빰@!",
      personType: "C",
    },
    {
      id: 4,
      category: "인형",
      brand: "WitchB",
      productName: "재인 인형",
      image: "",
      price: "18000",
      description: "어쩌구 저쩌구 훌라 훌라 훌라 나는야~~ 멋진 토마토 빰빰@!",
      personType: "D",
    },
    {
      id: 5,
      category: "디퓨저",
      brand: "WitchA",
      productName: "갑열 디퓨저",
      image: "",
      price: "18000",
      description: "어쩌구 저쩌구 훌라 훌라 훌라 나는야~~ 멋진 토마토 빰빰@!",
      personType: "A",
    },
    {
      id: 6,
      category: "디퓨저",
      brand: "WitchB",
      productName: "은비 디퓨저",
      image: "",
      price: "18000",
      description: "어쩌구 저쩌구 훌라 훌라 훌라 나는야~~ 멋진 토마토 빰빰@!",
      personType: "B",
    },
    {
      id: 7,
      category: "디퓨저",
      brand: "WitchA",
      productName: "재인 디퓨저",
      image: "",
      price: "18000",
      description: "어쩌구 저쩌구 훌라 훌라 훌라 나는야~~ 멋진 토마토 빰빰@!",
      personType: "C",
    },
    {
      id: 8,
      category: "디퓨저",
      brand: "WitchB",
      productName: "갑열 디퓨저",
      image: "",
      price: "18000",
      description: "어쩌구 저쩌구 훌라 훌라 훌라 나는야~~ 멋진 토마토 빰빰@!",
      personType: "D",
    },
    {
      id: 9,
      category: "드림캐쳐",
      brand: "WitchA",
      productName: "은비 드림캐쳐",
      image: "",
      price: "18000",
      description: "어쩌구 저쩌구 훌라 훌라 훌라 나는야~~ 멋진 토마토 빰빰@!",
      personType: "A",
    },
    {
      id: 10,
      category: "드림캐쳐",
      brand: "WitchA",
      productName: "재인 드림캐쳐",
      image: "",
      price: "18000",
      description: "어쩌구 저쩌구 훌라 훌라 훌라 나는야~~ 멋진 토마토 빰빰@!",
      personType: "B",
    },
    {
      id: 11,
      category: "드림캐쳐",
      brand: "WitchB",
      productName: "갑열 드림캐쳐",
      image: "",
      price: "18000",
      description: "어쩌구 저쩌구 훌라 훌라 훌라 나는야~~ 멋진 토마토 빰빰@!",
      personType: "C",
    },
    {
      id: 12,
      category: "드림캐쳐",
      brand: "WitchB",
      productName: "은비 드림캐쳐",
      image: "",
      price: "18000",
      description: "어쩌구 저쩌구 훌라 훌라 훌라 나는야~~ 멋진 토마토 빰빰@!",
      personType: "D",
    },
  ];

export {products}